all: f1 f2 f3 f4 f5 f6 f7 f8

f1:
	sleep 11
f2:
	sleep 12
f3:
	sleep 13
f4:
	sleep 14
f5:
	sleep 15
f6:
	sleep 16
f7:
	sleep 17

f8:
	echo 1
	echo 2 1>&2
	echo 3
	echo 4 1>&2
	echo 5
	echo 6 1>&2
	echo 7
	echo 8 1>&2
	echo 9
	echo 10 1>&2
	echo 11
	echo 12 1>&2
