all: f1 f2 f3 f4 f5 f6 f7 f8 f9 f10

.PHONY: f1 f2 f3 f4 f5 f6 f7 f8 f9 f10
f1 f2 f3 f4 f5 f6 f7 f8 f9 f10:
	 make f
	 make f
	 make f
	 make f
	 make f
	 make f
	 make f
	 make f
	 make f
	 make f

.PHONY: f
f:
	date
